# fly.toml app configuration file generated for dellymoon on 2024-03-24T17:20:08-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dellymoon'
primary_region = 'qro'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
[deploy]
  release_command = "./bin/rails db:prepare"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

